api:
  build: .
  ports:
    - "4567:80"
  links:
    - "db"
  environment:
    - DATABASE_HOST=db
    - DATABASE_NAME=sinatra
    - DATABASE_USER=sinatra
    - DATABASE_PASSWORD=sinatra
db:
  image: "postgres"
  environment:
    - POSTGRES_USER=sinatra
    - POSTGRES_PASSWORD=sinatra
  ports:
    - "5432:5432"
